src/Entity/Chef.php
<?php

namespace App\Entity;

use App\Repository\ChefRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ChefRepository::class)
 */
class Chef
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $date_recrutement;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getDateRecrutement(): ?string
    {
        return $this->date_recrutement;
    }

    public function setDateRecrutement(string $date_recrutement): self
    {
        $this->date_recrutement = $date_recrutement;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }
}

src/Controller/ChefController.php
<?php

namespace App\Controller;
use App\Entity\Chef;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeInterface;
class ChefController extends AbstractController
{
    /**
     * @Route("/chef", name="chef")
     */
    public function index(): Response
    {
        return $this->render('chef/index.html.twig', [
            'controller_name' => 'ChefController',
        ]);
    }
    /**
    * @route("/ajoutchef" , name="ajoutchef")
    */
   public function ajoutchef(Request $request )
   {
        if($request->isMethod('POST'))
        {

        $nom = $request->request->get('nom');
        $prenom = $request->request->get('prenom');
        $photo = $request->request->get('photo');
        $adresse = $request->request->get('adresse');
        $date_rec = $request->request->get('date');
        $telephone = $request->request->get('telephone');
        $c = $this->getDoctrine()->getManager();
        $chef = new Chef();
        $chef->setNom($nom);
        $chef->setPrenom($prenom);
        $chef->setImage($photo);
        $chef->setAdresse($adresse);
        $chef->setTelephone($telephone);
        $chef->setDateRecrutement($date_rec);
        $c->persist($chef);
        $c->flush();
      
        }
        return $this->render('chef/ajouterchef.html.twig');
   }
  
  //afficher la page de modification du freelancer et remplir les champs
    /**
     * @Route("/modificationchef/{id}", name="modificationchef")
     */
    public function modificationchef(Request $request,$id)
    
    {
        $em=$this->getDoctrine()->getManager();
        $repo=$em->getRepository( Chef::class);
        $listetache =$repo->find( $id);
        return $this->render('chef/modifchef.html.twig', [
            'chef' => $listetache,
        ]);
    } 
       //afficher les données d'un chef
    /**
     * @Route("/detailschef/{id}", name="detailschef")
     */
    public function detailschef(Request $request,$id)
    
    {
        $c=$this->getDoctrine()->getManager();
        $repo=$c->getRepository( Chef::class);
        $listechef =$repo->find( $id);
        return $this->render('chef/detailschef.html.twig', [
            'chef' => $listechef,
        ]);
    } 

    
      //pour modifier un chef
    /**
     * @route("/modifchef11" , name="modifchef11")
     */
    public function modifchef (Request $request )
    {
      
            $params = $request->query->all();
            $id = $request->get('id');
            $nom = $request->request->get('nom');
            $prenom = $request->get('prenom');
            $adresse = $request->get('adresse');
            $img = $request->get('photo');
            $date = $request->get('date');
            $tel = $request->get('telephone');
            $em = $this->getDoctrine()->getRepository(Chef::class)->find($id);
            $entity=$this->getDoctrine()->getManager();
            $em->setNom($nom);
            $em->setPrenom($prenom);
            $em->setAdresse($adresse);
            $em->setTelephone($tel);
            $em->setImage($img);
            $em->setDateRecrutement($date);
            $entity->persist($em);
            $entity->flush();
            return $this->redirectToRoute("listchef");    
        } 
    

   //pour afficher la liste des chefs dans le dashboard de l'admin
    /**
     * @Route("listchef", name="listchef")
     */
    public function listchef(Request $request)
    
    {
        $c=$this->getDoctrine()->getManager();
        $repo=$c->getRepository( Chef::class);
        $listchef =$repo->findAll();
        return $this->render('chef/listchef.html.twig', [
            'chefs' => $listchef,
        ]);
    }
   
  
      //pour supprimer un chef
    /**
     * @Route("deletechef/{id}", name="deletechef")
     */
    public function delete(Request $request,$id) {
        $wantedUser = $this->getDoctrine()->getRepository(Chef::class)->find($id);
        if (!$wantedUser) {
            throw $this->createNotFoundException("User with id ".id." not found in the database !");
        }
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($wantedUser);
        $entityManager->flush();
        return($this->redirectToRoute('listchef'));
    }
}

templates/chef/ajouterchef.html.twig
{% extends "layout.html.twig" %}
{% block title %}
New Chef
{% endblock %}
{% block res_body %}
<div class="content-body">
            <div class="container-fluid">
                <div class="row page-titles mx-0">
                    <div class="col-sm-6 p-md-0">
                        <div class="welcome-text">
                            <h4></h4>
                            <p class="mb-0"></p>
                        </div>
                    </div>
                    <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="javascript:void(0)">Chef</a></li>
                            <li class="breadcrumb-item active"><a href="javascript:void(0)">Ajout</a></li>
                        </ol>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Ajouter un nouveau chef</h4>
                            </div>
                            <div class="card-body">
                                <div class="form-validation">
                                    <form class="form-valide"  method="post" action="{{ path('ajoutchef') }}">
                                        <div class="row">
                                            <div class="col-xl-6">
                                                
                                               
                                                <div class="form-group row">
                                                    <label class="col-lg-4 col-form-label" >Nom
                                                        <span class="text-danger">*</span>
                                                    </label>
                                                    <div class="col-lg-6">
                                                        <input type="text" class="form-control"  name="nom" >
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label class="col-lg-4 col-form-label" >Prenom <span
                                                            class="text-danger">*</span>
                                                    </label>
                                                    <div class="col-lg-6">
                                                        <input type="text" class="form-control"  name="prenom">
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label class="col-lg-4 col-form-label" >photo
                                                        <span class="text-danger">*</span>
                                                    </label>
                                                    <div class="col-lg-6">
                                                        <input type="text" class="form-control"  name="photo" >
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label class="col-lg-4 col-form-label" >adresse
                                                        <span class="text-danger">*</span>
                                                    </label>
                                                    <div class="col-lg-6">
                                                        <input type="text" class="form-control"  name="adresse" >
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label class="col-lg-4 col-form-label" >telephone
                                                        <span class="text-danger">*</span>
                                                    </label>
                                                    <div class="col-lg-6">
                                                        <input type="text" class="form-control"  name="telephone" >
                                                    </div>
                                                </div>
                                                 <div class="form-group row">
                                                    <label class="col-lg-4 col-form-label" >date recrutement
                                                        <span class="text-danger">*</span>
                                                    </label>
                                                    <div class="col-lg-6">
                                                        <input type="text" class="form-control"  name="date" >
                                                    </div>
                                                </div>
                                                
                                                <div class="form-group row">
                                                    <div class="col-lg-8 ml-auto">
                                                        <button type="submit" class="btn btn-primary">Submit</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                   
                </div>
            </div>
        </div>{% endblock %}

templates/chef/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ChefController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/wamp64/www/Restaurant/src/Controller/ChefController.php'|file_link(0) }}">src/Controller/ChefController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/wamp64/www/Restaurant/templates/chef/index.html.twig'|file_link(0) }}">templates/chef/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/chef/listchef.html.twig
{% extends "layout.html.twig" %}
{% block title %}
List chef
{% endblock %}
{% block res_body %}
       <div class="content-body">
            <div class="container-fluid">
                <div class="row page-titles mx-0">
                    <div class="col-sm-6 p-md-0">
                        <div class="welcome-text">
                            <h4>Hi, welcome back!</h4>
                            <p class="mb-0"></p>
                        </div>
                    </div>
                    <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="javascript:void(0)">Restaurant</a></li>
                            <li class="breadcrumb-item active"><a href="javascript:void(0)">Chefs</a></li>
                        </ol>
                    </div>
                </div>
                 <ul class="header-dropdown">
                <li><a href="{{path('ajoutchef')}}" class="btn btn-info" role="button">Ajouter</a></li>
              </ul>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-sm mb-0 table-striped">
                                        <thead>
                                            <tr>
                                                <th class=" pr-3">
													<div class="custom-control custom-checkbox mx-2">
														<input type="checkbox" class="custom-control-input" id="checkAll">
														<label class="custom-control-label" for="checkAll"></label>
													</div>
                                                </th>
                                                <th>Name</th>
                                                <th>Email</th>
                                                <th>Phone</th>
                                                <th class=" pl-5" style="min-width: 200px;">Billing Address
                                                </th>
                                                <th>Joined</th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody id="customers">
                                         {% for chef in chefs %}
                                            <tr class="btn-reveal-trigger">
                                                <td class="py-2">
                                                    <div class="custom-control custom-checkbox mx-2">
														<input type="checkbox" class="custom-control-input" id="checkbox1">
														<label class="custom-control-label" for="checkbox1"></label>
													</div>
                                                </td>
                                                <td class="py-3">
                                                    <a href="#">
                                                        <div class="media d-flex align-items-center">
                                                            <div class="avatar avatar-xl mr-2">
                                                                <div class=""> <img src="{{asset('assets/images/profile/profile.png')}}" width="30" alt="" />
                                                                </div>
                                                            </div>
                                                            <div class="media-body">
                                                                <h5 class="mb-0 fs--1">{{chef.nom}} {{chef.prenom}}</h5>
                                                            </div>
                                                        </div>
                                                    </a>
                                                </td>
                                                <td class="py-2"><a
                                                        href="mailto:ricky@example.com">info@example.com</a></td>
                                                <td class="py-2"> <a href="tel:2012001851">{{chef.telephone}}</a></td>
                                                <td class="py-2 pl-5">{{chef.adresse}}</td>
                                                <td class="py-2">{{chef.dateRecrutement}}</td>
                                                <td class="py-2 text-right">
                                                    <div class="dropdown"><button class="btn btn-primary tp-btn-light sharp" type="button" data-toggle="dropdown"><span class="fs--1"><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="18px" height="18px" viewBox="0 0 24 24" version="1.1"><g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><rect x="0" y="0" width="24" height="24"></rect><circle fill="#000000" cx="5" cy="12" r="2"></circle><circle fill="#000000" cx="12" cy="12" r="2"></circle><circle fill="#000000" cx="19" cy="12" r="2"></circle></g></svg></span></button>
                                                        <div class="dropdown-menu dropdown-menu-right border py-0">
                                                            <div class="py-2"><a class="dropdown-item" href="{{path('modificationchef',{'id':chef.id})}}">Edit</a><a class="dropdown-item text-danger"  href="{{path('deletechef',{'id':chef.id})}}">Delete</a></div>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}

templates/chef/modifchef.html.twig
{% extends "layout.html.twig" %}
{% block title %}
modifchef
{% endblock %}
{% block res_body %}
<div class="content-body">
            <div class="container-fluid">
                <div class="row page-titles mx-0">
                    <div class="col-sm-6 p-md-0">
                        <div class="welcome-text">
                            <h4>Hi, welcome back!</h4>
                            <p class="mb-0"></p>
                        </div>
                    </div>
                    <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="javascript:void(0)">Chef</a></li>
                            <li class="breadcrumb-item active"><a href="javascript:void(0)">Modification</a></li>
                        </ol>
                    </div>
                </div>
                <!-- row -->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Form Validation</h4>
                            </div>
                            <div class="card-body">
                                <div class="form-validation">
                                    <form class="form-valide"  method="post" action="{{ path('modifchef11') }}">
                                        <div class="row">
                                            <div class="col-xl-6">
                                             <div class="form-group row">
                                                    <label class="col-lg-4 col-form-label" >id
                                                        <span class="text-danger">*</span>
                                                    </label>
                                                    <div class="col-lg-6">
                                                        <input type="text" class="form-control"  name="id" value={{chef.id}}>
                                                    </div>
                                                </div>
                                                 
                                                <div class="form-group row">
                                                    <label class="col-lg-4 col-form-label" >Nom
                                                        <span class="text-danger">*</span>
                                                    </label>
                                                    <div class="col-lg-6">
                                                        <input type="text" class="form-control"  name="nom" value={{chef.nom}}>
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label class="col-lg-4 col-form-label" >Prenom <span
                                                            class="text-danger">*</span>
                                                    </label>
                                                    <div class="col-lg-6">
                                                        <input type="text" class="form-control"  name="prenom" value={{chef.prenom}}>
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label class="col-lg-4 col-form-label" >photo
                                                        <span class="text-danger">*</span>
                                                    </label>
                                                    <div class="col-lg-6">
                                                        <input type="text" class="form-control"  name="photo" value={{chef.image}}>
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label class="col-lg-4 col-form-label" >adresse
                                                        <span class="text-danger">*</span>
                                                    </label>
                                                    <div class="col-lg-6">
                                                        <input type="text" class="form-control"  name="adresse" value={{chef.adresse}}>
                                                    </div>
                                                </div>
                                                <div class="form-group row">
                                                    <label class="col-lg-4 col-form-label" >telephone
                                                        <span class="text-danger">*</span>
                                                    </label>
                                                    <div class="col-lg-6">
                                                        <input type="text" class="form-control"  name="telephone" value={{chef.telephone}}>
                                                    </div>
                                                </div>
                                                 <div class="form-group row">
                                                    <label class="col-lg-4 col-form-label" >date recrutement
                                                        <span class="text-danger">*</span>
                                                    </label>
                                                    <div class="col-lg-6">
                                                        <input type="text" class="form-control"  name="date" value={{chef.dateRecrutement}} >
                                                    </div>
                                                </div>
                                                
                                                <div class="form-group row">
                                                    <div class="col-lg-8 ml-auto">
                                                        <button type="submit" class="btn btn-primary">Submit</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                   
                </div>
            </div>
        </div>{% endblock %}